### ISSUE TITLE
Chat-with-pdf starter apps fail for some pdf files

### ISSUE THREAD

**Issue by ananis25** [neondatabase/examples#20]
## Steps to reproduce

Upload this file to the sample app at - https://github.com/neondatabase/examples/tree/main/ai/langchain/chat-with-pdf-nextjs
[rust-cheat-sheet.pdf](https://github.com/user-attachments/files/16203643/rust-cheat-sheet.pdf)

## Expected result

Invalid characters are ignored, and the rest of the document still gets uploaded.

## Actual result

No parts of the document get added

## Environment
NA

## Logs, links
```bash
 ✓ Compiled /api/upsert in 4.4s (1327 modules)
error: invalid byte sequence for encoding "UTF8": 0x00 error: invalid byte sequence for encoding "UTF8": 0x00
    at /home/ubuntu/repos/neon-ai-apps/chat-with-pdf-nextjs/node_modules/pg/lib/client.js:526:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PGVectorStore.add (webpack-internal:///(rsc)/./node_modules/llamaindex/dist/storage/vectorStore/PGVectorStore.js:167:32)
    at async addNodesToVectorStores (webpack-internal:///(rsc)/./node_modules/llamaindex/dist/ingestion/IngestionPipeline.js:145:28)
    at async VectorStoreIndex.insertNodes (webpack-internal:///(rsc)/./node_modules/llamaindex/dist/indices/vectorStore/index.js:575:9)
    at async VectorStoreIndex.buildIndexFromNodes (webpack-internal:///(rsc)/./node_modules/llamaindex/dist/indices/vectorStore/index.js:489:9)
    at async VectorStoreIndex.init (webpack-internal:///(rsc)/./node_modules/llamaindex/dist/indices/vectorStore/index.js:439:13)
    at async VectorStoreIndex.fromDocuments (webpack-internal:///(rsc)/./node_modules/llamaindex/dist/indices/vectorStore/index.js:517:16)
    at async POST (webpack-internal:///(rsc)/./app/api/upsert/route.ts:29:5)
    at async /home/ubuntu/repos/neon-ai-apps/chat-with-pdf-nextjs/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:55038
    at async ek.execute (/home/ubuntu/repos/neon-ai-apps/chat-with-pdf-nextjs/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:45808)
    at async ek.handle (/home/ubuntu/repos/neon-ai-apps/chat-with-pdf-nextjs/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:56292)
    at async doRender (/home/ubuntu/repos/neon-ai-apps/chat-with-pdf-nextjs/node_modules/next/dist/server/base-server.js:1377:42)
    at async cacheEntry.responseCache.get.routeKind (/home/ubuntu/repos/neon-ai-apps/chat-with-pdf-nextjs/node_modules/next/dist/server/base-server.js:1599:28)
    at async DevServer.renderToResponseWithComponentsImpl (/home/ubuntu/repos/neon-ai-apps/chat-with-pdf-nextjs/node_modules/next/dist/server/base-server.js:1507:28)
    at async DevServer.renderPageComponent (/home/ubuntu/repos/neon-ai-apps/chat-with-pdf-nextjs/node_modules/next/dist/server/base-server.js:1931:24)
    at async DevServer.renderToResponseImpl (/home/ubuntu/repos/neon-ai-apps/chat-with-pdf-nextjs/node_modules/next/dist/server/base-server.js:1969:32)
    at async DevServer.pipeImpl (/home/ubuntu/repos/neon-ai-apps/chat-with-pdf-nextjs/node_modules/next/dist/server/base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (/home/ubuntu/repos/neon-ai-apps/chat-with-pdf-nextjs/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/home/ubuntu/repos/neon-ai-apps/chat-with-pdf-nextjs/node_modules/next/dist/server/base-server.js:816:17)
    at async /home/ubuntu/repos/neon-ai-apps/chat-with-pdf-nextjs/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/home/ubuntu/repos/neon-ai-apps/chat-with-pdf-nextjs/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/home/ubuntu/repos/neon-ai-apps/chat-with-pdf-nextjs/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/home/ubuntu/repos/neon-ai-apps/chat-with-pdf-nextjs/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/home/ubuntu/repos/neon-ai-apps/chat-with-pdf-nextjs/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/home/ubuntu/repos/neon-ai-apps/chat-with-pdf-nextjs/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/home/ubuntu/repos/neon-ai-apps/chat-with-pdf-nextjs/node_modules/next/dist/server/lib/start-server.js:141:13) {
  length: 146,
  severity: 'ERROR',
  code: '22021',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'unnamed portal parameter $4',
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'mbutils.c',
  line: '1723',
  routine: 'report_invalid_encoding'
}
```

**Comment by rishi-raj-jain** [comment]
Appreciate the issue reproduction and report.

Fixed in https://github.com/neondatabase/examples/commit/60f4d8f6786a2b4b97684d17e7f5794ba98899d0 per https://github.com/langchain-ai/langchainjs/pull/3628/files.
